application: chentweetsanalyzer
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /bootstrap
  static_dir: bootstrap

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: cloud.app
  
libraries:
- name: jinja2
  version: latest  